POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3MTE0NjUwNTIsInVzZXJJZCI6MX0.0sOVATtwzf5V_W4RLvniINIQO0bvSD6ArqILiyJ4844

{
  "name": "Test event ay222",
  "description": "This is a test event",
  "location": "A test location",
  "dateTime": "2025-01-01T15:30:00.000Z"
}